# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{atrium}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hiten Parmar"]
  s.date = %q{2011-04-02}
  s.default_executable = %q{atrium}
  s.description = %q{Instant webserver.}
  s.email = %q{hrparmar@gmail.com}
  s.executables = ["atrium"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Atrium.gemspec",
    "README.md",
    "Rakefile",
    "VERSION",
    "atrium.gemspec",
    "bin/atrium",
    "pkg/Atrium-0.4.0.gem",
    "pkg/atrium-0.4.0.gem",
    "pkg/atrium-1.0.0.gem"
  ]
  s.homepage = %q{http://h10labs.com}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.3}
  s.summary = %q{Instant webserver.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thin>, [">= 0"])
      s.add_runtime_dependency(%q<rack>, [">= 0"])
    else
      s.add_dependency(%q<thin>, [">= 0"])
      s.add_dependency(%q<rack>, [">= 0"])
    end
  else
    s.add_dependency(%q<thin>, [">= 0"])
    s.add_dependency(%q<rack>, [">= 0"])
  end
end

